version: '3.8'
services:
  graphql-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    depends_on:
      - postgres-db
      - redis
    environment:
      - DATABASE_HOST=postgres-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=mydatabase
      - DATABASE_USERNAME=myusername
      - DATABASE_PASSWORD=mypassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  postgres-db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - ./data:/var/lib/postgresql/data:Z
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/data
